Repository net-utilities/BigIPReport, pull requests merged in 2021-04, with the labels that each got.

#39 Sync status and non primary node active indications in device status (Closes #38)
  bigipreport.ps1
  bigipreportconfig.xml
  js-src/SiteDataInterfaces/ILoadbalancer.ts
  js-src/bigipreport.ts
  underlay/css/bigipreportstyle.css
  underlay/js/bigipreport.js
Labels: enhancement

#51 Bump version
  bigipreport.ps1
  bigipreportconfig.xml
Labels: enhancement

#53 Fixing the credentials bug
  bigipreport.ps1
Labels: bug

#57 Comment cleanup, call jobs jobs, Get-SupportState
  bigipreport.ps1
Labels: enhancement

#56 Feature/slack alerts (Closes #48, #58, #59)
  .github/workflows/VersionValidation.yml
  .gitignore
  HelpScripts/TroubleShoot.ps1
  bigipreport.ps1
  bigipreportconfig.xml
  js-src/PoolDetails/showPoolDetails.ts
  js-src/SiteDataInterfaces/ILoadbalancer.ts
  js-src/SiteDataInterfaces/ISiteData.ts
  js-src/SiteDataInterfaces/IState.ts
  js-src/bigipreport.ts
  modules/Get-ExpiredCertificates.ps1
  modules/Get-SupportEntitlements.ps1
  modules/Send-SlackCertificateAlert.ps1
  modules/Send-SlackSupportStateAlert.ps1
  nginx/nginx.conf
  underlay/css/bigipreportstyle.css
  underlay/js/MemberPolling/IPollingResponse.js
  underlay/js/PoolDetails/showPoolDetails.js
  underlay/js/SiteDataInterfaces/IASMPolicy.js
  underlay/js/SiteDataInterfaces/ICertificate.js
  underlay/js/SiteDataInterfaces/IDataGroup.js
  underlay/js/SiteDataInterfaces/IDeviceGroup.js
  underlay/js/SiteDataInterfaces/IIrule.js
  underlay/js/SiteDataInterfaces/IKnowndevice.js
  underlay/js/SiteDataInterfaces/ILoadbalancer.js
  underlay/js/SiteDataInterfaces/ILoggedErrors.js
  underlay/js/SiteDataInterfaces/IMemberStates.js
  underlay/js/SiteDataInterfaces/IMonitor.js
  underlay/js/SiteDataInterfaces/INAT.js
  underlay/js/SiteDataInterfaces/IPool.js
  underlay/js/SiteDataInterfaces/IPreferences.js
  underlay/js/SiteDataInterfaces/ISiteData.js
  underlay/js/SiteDataInterfaces/IVirtualServer.js
  underlay/js/bigipreport.js
  underlay/js/jquery.highlight.js
Labels: bug, enhancement
